from tkinter import *
window=Tk()
window.geometry("400x600")
Title=Label(window,text="Jumbled word game")
Title.place(x=150,y=50)
Word=Label(window,text="Word")
Word.place(x=150,y=200)
Enter=Entry(window)
Enter.place(x=150,y=300)
Answer_check=Button(window,text="Check answer")
Answer_check.place(x=150,y=400)
Reset=Button(window,text="Reset")
Reset.place(x=150,y=500)
window.mainloop()